version: '3.8'
services:
  web:
    platform: linux/amd64
    container_name: odoo16
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: -d odoo16 --addons=/mnt/extra-addons --without-demo=True $odooparams
    build:
        dockerfile: ./Dockerfile
        ssh: ["default"]
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: